[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true

# Optimizer
optimizer = true
optimizer_runs = 200_000_000

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]